apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service-app
  labels:
    app: address-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-service-app
  template:
    metadata:
      labels:
        app: address-service-app
    spec:
      containers:
        - name: address-service-app
          image: explaincs/address-service:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8092

---
apiVersion: v1
kind: Service
metadata:
  name: address-service-svc
spec:
  ports:
    - targetPort: 8092
      port: 80
  selector:
    app: address-service-app
