apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
  labels:
    app: cloud-config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server-app
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      containers:
        - name: cloud-config-server-app
          image: explaincs/cloud-config-server:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8787

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server-svc
spec:
  ports:
    - targetPort: 8787
      port: 80
  selector:
    app: cloud-config-server-app
