apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service-app
  labels:
    app: student-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : student-service-app
  template:
    metadata:
      labels:
        app: student-service-app
    spec:
      containers:
      - name: student-service-app
        image: explaincs/student-service:1.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8092

---

kind: Service
apiVersion: v1
metadata:
  name:  student-service-svc
spec:
  selector:
    app:  student-service-app
  ports:
  - port:  80
    targetPort:  8092
